### ISSUE TITLE
Test docker socket query failed

### ISSUE THREAD

**Issue by jialiang-yin** [kerams/docker-exporter#2]
Hello @kerams,

I was trying to export all docker container metrics using your docker-exporter image, but some error occurs. 

> promtheus_docker-exporter_1  | thread 'main' panicked at 'Test Docker socket query failed.', src/main.rs:46:36
promtheus_docker-exporter_1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I have the docker engine as following:

> Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:41 2023
 OS/Arch:           linux/arm64
 Context:           default

> Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:41 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

The minimum version is 1.12, this should be suitable with the compatibility requirement.

**Comment by kerams** [comment]
That would indicate `/var/run/docker.sock` is not accessible to the exporter. What run command/compose file do you use to set it up? Are you mounting the socket as suggested in the readme? Perhaps the Docker socket on your host is located elsewhere?

**Comment by jialiang-yin** [comment]
Hi,

I have double checked the location of docker.sock, it is right there in /var/run/docker.sock. 
`srw-rw----  1 root docker    0 May  3 15:52 docker.sock`

docker.sock I have already mounted it to container.

The compose file, that I used to set them up is here:

```
version: "2.4"
services:
  promtheus_node-exporter:
    image: "prom/node-exporter-linux-arm64"
    command: 
      - --path.rootfs=/hostfs
    ports:
      - 0.0.0.0:9100:9100
    networks:
      - fastiot-net
    volumes:
      - /:/hostfs
    restart: always
    depends_on:
      - promtheus_nats-exporter


  promtheus_docker-exporter:
    image: "keramss/docker-exporter:2023-04-25T19-58-53Z"
    ports:
      - 0.0.0.0:9417:9417
    networks:
      - fastiot-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    depends_on:
      - promtheus_nats-exporter

  promtheus_nats-exporter:
    image: "docker.dev.ivv-dd.fhg.de:5000/prometheus-nats-exporter"
    command:
      - http://nats:8222
    ports:
      - 0.0.0.0:7777:7777
    networks:
      - fastiot-net
    restart: always

networks:
  fastiot-net:
```
